Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 
FCIF
scmpsw73new 
SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 
SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moi
fn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moifn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moifn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moifn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moifn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moifn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moifn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 
surensu777@gmail.com

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moifn ph
.	order in db with pending status.
See scmpsw73new.moi
Identification Data
Test Case Name	tptrans_geni_scmp_processing
Purpose	To check processing of
an order establishing an SCMP group which has 3
members with non-circular hunting.
Requirements Doc.
Requirements ID	
Author	Suren Sarkisian
Tester	Suren Sarkisian
Test Case Management Category
Feature	SCMP
Client	ALL
Test Phases	A.P
Test Steps	4
Priority	M
Automatable? 	N
Case Data	Work directory: /marchplus/test/MANUAL/30.0/TPTRANS/SCMP 

FCIF
scmpsw73new 

SW ID=73 
Method	

1.1.1	Test Case Identifier.Seq No
Test Step	Test Phase	Action	Results/Comments/Data/
References
1	A.P	Execute

tptrans scmpsw73new /tmp/out	tptrans parsed file and generate
2 output files:
fcif
out – generated by tptrans
outg – generated by geni
2	A.P	Compare /tmp/out with scmpsw73new.out 	Out Files content is the same.
3	A.P	Compare /tmp/outg with scmpsw73new.outg	Out Files content is the same.
4	A.P	Execute

moi
fn ph
.	order in db with pending status.
See scmpsw73new.moi